# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouin1vkc3SM1jkKUjHdhnkj0Xsv0lSIh
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

acne_triggers = [
    "coconut oil", "isopropyl myristate", "lanolin", "laureth-4",
    "myristyl myristate", "oleic acid", "sodium lauryl sulfate"
]

@app.route("/check_ingredients", methods=["POST"])
def check_ingredients():
    data = request.get_json()
    ingredients_text = data.get("ingredients", "").lower()
    found_triggers = []

    for trigger in acne_triggers:
        if trigger in ingredients_text:
            found_triggers.append(trigger)

    response = {
        "total_risky": len(found_triggers),
        "risky_ingredients": found_triggers
    }
    return jsonify(response)

if __name__ == "__main__":
    app.run(debug=True)